baseURL: https://ojasb.xyz/
defaultContentLanguage: en
locale: en-us
pluralizeListTitles: false
timeZone: America/Chicago
title: Ojas Bhagavath
enableRobotsTXT: true
disableKinds:
    - taxonomy
    - term
