contact:
    - name: "email"
      title: "Email"
      url: "mailto:hi@ojasb.xyz"
      pre: "logos/gmail.svg"
      params:
          - username: "hi@ojasb.xyz"
          - color: "#EA4335"
      weight: 1
    - name: "telegram"
      title: "Telegram"
      url: "https://t.me/ojasbhagavath"
      pre: "logos/telegram.svg"
      params:
          - username: "@ojasbhagavath"
          - color: "#26A5E4"
      weight: 2
    - name: "discord"
      title: "Discord"
      url: "https://discord.com/users/757208743988428901"
      pre: "logos/discord.svg"
      params:
          - username: "Ojas#4523"
          - color: "#5865F2"
      weight: 3
connect:
    - name: "github"
      title: "GitHub"
      url: "https://github.com/ojas-bhagavath"
      pre: "logos/github.svg"
      params:
          - username: "ojas-bhagavath"
          - color: "#181717"
      weight: 1
    - name: "linkedin"
      title: "LinkedIn"
      url: "https://www.linkedin.com/in/ojas-bhagavath/"
      pre: "logos/linkedin.svg"
      params:
          - username: "ojas-bhagavath"
          - color: "#0A66C2"
      weight: 2
    - name: "stackexchange"
      title: "Math Stack Exchange"
      url: "https://math.stackexchange.com/users/774120/ojas-bhagavath"
      pre: "logos/stackexchange.svg"
      params:
          - username: "ojas-bhagavath"
          - color: "#1E5397"
      weight: 3
    - name: "letterboxd"
      title: "Letterboxd"
      url: "https://letterboxd.com/ojas_bhagavath/films"
      pre: "logos/letterboxd.svg"
      params:
          - username: "ojas_bhagavath"
          - color: "#202830"
      weight: 4
    # - name: "leetcode"
    #   title: "LeetCode"
    #   url: "https://leetcode.com/u/ojas-bhagavath/"
    #   pre: "logos/leetcode.svg"
    #   params:
    #       - username: "ojas-bhagavath"
    #       - color: "#FFA116"
    #   weight: 5
    # - name: "codeforces"
    #   title: "CodeForces"
    #   url: "https://codeforces.com/profile/ojasgb"
    #   pre: "logos/codeforces.svg"
    #   params:
    #       - username: "ojasgb"
    #       - color: "#1F8ACB"
    #   weight: 6
    - name: "researchgate"
      title: "ResearchGate"
      url: "https://www.researchgate.net/profile/Ojas-Bhagavath"
      pre: "logos/researchgate.svg"
      params:
          - username: "Ojas-Bhagavath"
          - color: "#00CCBB"
      weight: 7
    - name: "instagram"
      title: "Instagram"
      url: "https://www.instagram.com/ojas.bhagavath/"
      pre: "logos/instagram.svg"
      params:
          - username: "ojas.bhagavath"
          - color: "#FF0069"
      weight: 8
    - name: "monkeytype"
      title: "monkeytype"
      url: "https://monkeytype.com/profile/ojas-bhagavath"
      pre: "logos/monkeytype.svg"
      params:
          - username: "ojas-bhagavath"
          - color: "#E2B714"
      weight: 9
    - name: "pinterest"
      title: "Pinterest"
      url: "https://pin.it/4i6Q7SAod"
      pre: "logos/pinterest.svg"
      params:
          - username: "obhagavath"
          - color: "#BD081C"
      weight: 10
