author: "Ojas Bhagavath"
description: "This is the website of Ojas Bhagavath—a mathematician, a freetime artist, and a hobbyist programmer."
sitemap:
    excludedKinds:
        - "taxonomy"
        - "term"
